matches:
  - trigger: ";alpha"
    label: "Greek Alpha"
    replace: "α"
  - trigger: ";beta"
    label: "Greek Beta"
    replace: "β"
  - trigger: ";gamma"
    label: "Greek Gamma"
    replace: "γ"
  - trigger: ";delta"
    label: "Greek Delta"
    replace: "δ"
  - trigger: ";epsilon"
    label: "Greek Epsilon"
    replace: "ε"
  - trigger: ";zeta"
    label: "Greek Zeta"
    replace: "ζ"
  - trigger: ";eta"
    label: "Greek Eta"
    replace: "η"
  - trigger: ";theta"
    label: "Greek Theta"
    replace: "θ"
  - trigger: ";iota"
    label: "Greek Iota"
    replace: "ι"
  - trigger: ";kappa"
    label: "Greek Kappa"
    replace: "κ"
  - trigger: ";lambda"
    label: "Greek Lambda"
    replace: "λ"
  - trigger: ";mu"
    label: "Greek Mu"
    replace: "μ"
  - trigger: ";nu"
    label: "Greek Nu"
    replace: "ν"
  - trigger: ";xi"
    label: "Greek Xi"
    replace: "ξ"
  - trigger: ";omicron"
    label: "Greek Omicron"
    replace: "ο"
  - trigger: ";pi"
    label: "Greek Pi"
    replace: "π"
  - trigger: ";rho"
    label: "Greek Rho"
    replace: "ρ"
  - trigger: ";sigma"
    label: "Greek Sigma"
    replace: "σ"
  - trigger: ";tau"
    label: "Greek Tau"
    replace: "τ"
  - trigger: ";upsilon"
    label: "Greek Upsilon"
    replace: "υ"
  - trigger: ";phi"
    label: "Greek Phi"
    replace: "φ"
  - trigger: ";chi"
    label: "Greek Chi"
    replace: "χ"
  - trigger: ";psi"
    label: "Greek Psi"
    replace: "ψ"
  - trigger: ";omega"
    label: "Greek Omega"
    replace: "ω"