matches:
  # Superscript (positive)
  - trigger: "^^2"
    label: "Superscript - 2"
    replace: "²"
  - trigger: "^^3"
    label: "Superscript - 3"
    replace: "³"
  - trigger: "^^4"
    label: "Superscript - 4"
    replace: "⁴"
  - trigger: "^^5"
    label: "Superscript - 5"
    replace: "⁵"
  - trigger: "^^6"
    label: "Superscript - 6"
    replace: "⁶"
  - trigger: "^^7"
    label: "Superscript - 7"
    replace: "⁷"
  - trigger: "^^8"
    label: "Superscript - 8"
    replace: "⁸"
  - trigger: "^^9"
    label: "Superscript - 9"
    replace: "⁹"

  # Superscript (negative)
  - trigger: "^^-2"
    label: "Superscript - -2"
    replace: "⁻²"
  - trigger: "^^-3"
    label: "Superscript - -3"
    replace: "⁻³"
  - trigger: "^^-4"
    label: "Superscript - -4"
    replace: "⁻⁴"
  - trigger: "^^-5"
    label: "Superscript - -5"
    replace: "⁻⁵"
  - trigger: "^^-6"
    label: "Superscript - -6"
    replace: "⁻⁶"
  - trigger: "^^-7"
    label: "Superscript - -7"
    replace: "⁻⁷"
  - trigger: "^^-8"
    label: "Superscript - -8"
    replace: "⁻⁸"
  - trigger: "^^-9"
    label: "Superscript - -9"
    replace: "⁻⁹"

  # Subscript (positive)
  - trigger: "__1"
    label: "Subscript - 1"
    replace: "₁"
  - trigger: "__2"
    label: "Subscript - 2"
    replace: "₂"
  - trigger: "__3"
    label: "Subscript - 3"
    replace: "₃"
  - trigger: "__4"
    label: "Subscript - 4"
    replace: "₄"
  - trigger: "__5"
    label: "Subscript - 5"
    replace: "₅"
  - trigger: "__6"
    label: "Subscript - 6"
    replace: "₆"
  - trigger: "__7"
    label: "Subscript - 7"
    replace: "₇"
  - trigger: "__8"
    label: "Subscript - 8"
    replace: "₈"
  - trigger: "__9"
    label: "Subscript - 9"
    replace: "₉"

  # Subscript (negative)
  - trigger: "__-1"
    label: "Subscript - -1"
    replace: "₋₁"
  - trigger: "__-2"
    label: "Subscript - -2"
    replace: "₋₂"
  - trigger: "__-3"
    label: "Subscript - -3"
    replace: "₋₃"
  - trigger: "__-4"
    label: "Subscript - -4"
    replace: "₋₄"
  - trigger: "__-5"
    label: "Subscript - -5"
    replace: "₋₅"
  - trigger: "__-6"
    label: "Subscript - -6"
    replace: "₋₆"
  - trigger: "__-7"
    label: "Subscript - -7"
    replace: "₋₇"
  - trigger: "__-8"
    label: "Subscript - -8"
    replace: "₋₈"
  - trigger: "__-9"
    label: "Subscript - -9"
    replace: "₋₉"
